#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("evfa.Resource", IsApplication=true)]

namespace evfa
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int eopshome = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int livesEVENTS = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int JobID = 2131034115;
			
			// aapt resource value: 0x7f050019
			public const int MyButton = 2131034137;
			
			// aapt resource value: 0x7f05000d
			public const int btnNewPrf = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btnSave = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int button1 = 2131034135;
			
			// aapt resource value: 0x7f05001b
			public const int ctvTitle = 2131034139;
			
			// aapt resource value: 0x7f05000e
			public const int fragmentContainer = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int gridLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05001a
			public const int imageView1 = 2131034138;
			
			// aapt resource value: 0x7f050013
			public const int lblJobAlloc = 2131034131;
			
			// aapt resource value: 0x7f05001c
			public const int rbTitleMr = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int rbTitleMrs = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int rbTitleMs = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int rbTitleOther = 2131034143;
			
			// aapt resource value: 0x7f050002
			public const int sampleTextView = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int tabHost2 = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int tableLayout1 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int tableLayout2 = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int tableRow1 = 2131034128;
			
			// aapt resource value: 0x7f050016
			public const int tableRow2 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int tableRow3 = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int tableRow4 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int tableRow5 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int tableRow6 = 2131034133;
			
			// aapt resource value: 0x7f050021
			public const int txtAdd1 = 2131034145;
			
			// aapt resource value: 0x7f050009
			public const int txtCategory = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int txtJobDate = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int txtJobDescription = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int txtJobTime = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int txtLocation = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int txtPriority = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int txtStatus = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int txtTeam = 2131034118;
			
			// aapt resource value: 0x7f050022
			public const int txtptAdd2 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int txtptAdd3 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int txtptAdd4 = 2131034148;
			
			// aapt resource value: 0x7f050027
			public const int txtptAge = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int txtptDOB = 2131034152;
			
			// aapt resource value: 0x7f050020
			public const int txtptName = 2131034144;
			
			// aapt resource value: 0x7f050025
			public const int txtptPCode = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int txtptTelno = 2131034150;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int eprfTab = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int jdTab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int JobDetails = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int prfTabpd = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int AcceptJob = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int AddLJob = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int JobDets = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int JobRef = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
