#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("evfa.Resource", IsApplication=true)]

namespace evfa
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Details = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int eops250 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int eops32 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int eopshome = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int eye32321 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int eye32322 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int livesEVENTS = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Users = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int JobID = 2131034115;
			
			// aapt resource value: 0x7f05001a
			public const int MyButton = 2131034138;
			
			// aapt resource value: 0x7f05000d
			public const int btnNewPrf = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btnSave = 2131034124;
			
			// aapt resource value: 0x7f050031
			public const int chkComplete = 2131034161;
			
			// aapt resource value: 0x7f05002d
			public const int chkInf = 2131034157;
			
			// aapt resource value: 0x7f050028
			public const int chkonO2 = 2131034152;
			
			// aapt resource value: 0x7f05003b
			public const int ctvDischID = 2131034171;
			
			// aapt resource value: 0x7f050040
			public const int ctvTitle = 2131034176;
			
			// aapt resource value: 0x7f050020
			public const int ctvavpu = 2131034144;
			
			// aapt resource value: 0x7f05003f
			public const int editText1 = 2131034175;
			
			// aapt resource value: 0x7f050000
			public const int fragmentContainer = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int gridLayout1 = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int imgmain = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int lblCallsign = 2131034140;
			
			// aapt resource value: 0x7f050018
			public const int lblDesc = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int lblGroup = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int lblJobTime = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int lblLoc = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int lblPriority = 2131034132;
			
			// aapt resource value: 0x7f050021
			public const int rbAVPUA = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int rbAVPUP = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int rbAVPUU = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int rbAVPUV = 2131034146;
			
			// aapt resource value: 0x7f05003c
			public const int rbDischHome = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int rbDischHosp = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int rbDischMedicalC = 2131034174;
			
			// aapt resource value: 0x7f050041
			public const int rbTitleMr = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int rbTitleMrs = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int rbTitleMs = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int rbTitleOther = 2131034180;
			
			// aapt resource value: 0x7f050002
			public const int sampleTextView = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int tableLayout1 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int tableRow1 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int tableRow2 = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int tableRow3 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int tableRow4 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int tableRow5 = 2131034135;
			
			// aapt resource value: 0x7f050046
			public const int txtAdd1 = 2131034182;
			
			// aapt resource value: 0x7f050036
			public const int txtAllergies = 2131034166;
			
			// aapt resource value: 0x7f05002b
			public const int txtBPDia = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int txtBPSys = 2131034154;
			
			// aapt resource value: 0x7f05002c
			public const int txtCBG = 2131034156;
			
			// aapt resource value: 0x7f05001d
			public const int txtCallsign = 2131034141;
			
			// aapt resource value: 0x7f050009
			public const int txtCategory = 2131034121;
			
			// aapt resource value: 0x7f050034
			public const int txtComplaint = 2131034164;
			
			// aapt resource value: 0x7f050019
			public const int txtDesc = 2131034137;
			
			// aapt resource value: 0x7f050032
			public const int txtError = 2131034162;
			
			// aapt resource value: 0x7f05001f
			public const int txtGroup = 2131034143;
			
			// aapt resource value: 0x7f050037
			public const int txtHistory = 2131034167;
			
			// aapt resource value: 0x7f050004
			public const int txtJobDate = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int txtJobDescription = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int txtJobTime = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int txtLoc = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int txtLocation = 2131034119;
			
			// aapt resource value: 0x7f050035
			public const int txtMeds = 2131034165;
			
			// aapt resource value: 0x7f05002e
			public const int txtNews = 2131034158;
			
			// aapt resource value: 0x7f050027
			public const int txtO2sats = 2131034151;
			
			// aapt resource value: 0x7f050008
			public const int txtPriority = 2131034120;
			
			// aapt resource value: 0x7f050026
			public const int txtPulse = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int txtResp = 2131034149;
			
			// aapt resource value: 0x7f05002f
			public const int txtSepsis = 2131034159;
			
			// aapt resource value: 0x7f05000b
			public const int txtStatus = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int txtTeam = 2131034118;
			
			// aapt resource value: 0x7f050029
			public const int txtTemp = 2131034153;
			
			// aapt resource value: 0x7f050030
			public const int txtTime = 2131034160;
			
			// aapt resource value: 0x7f05003a
			public const int txtTreatedBy = 2131034170;
			
			// aapt resource value: 0x7f050039
			public const int txtTreatedByPIN = 2131034169;
			
			// aapt resource value: 0x7f050038
			public const int txtTreatment = 2131034168;
			
			// aapt resource value: 0x7f050033
			public const int txtincidentArea = 2131034163;
			
			// aapt resource value: 0x7f050047
			public const int txtptAdd2 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int txtptAdd3 = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int txtptAdd4 = 2131034185;
			
			// aapt resource value: 0x7f05004c
			public const int txtptAge = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int txtptDOB = 2131034189;
			
			// aapt resource value: 0x7f050045
			public const int txtptName = 2131034181;
			
			// aapt resource value: 0x7f05004a
			public const int txtptPCode = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int txtptTelno = 2131034187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int eJob = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int eprfTab = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int jdTab = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int JobAlert = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ObsTab = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int prfDetails = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int prfTabdet = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int prfTabpd = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int AcceptJob = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int AddLJob = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int JobDets = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int JobRef = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
